### ISSUE TITLE
Tenant V2 Changes Errors

### ISSUE THREAD

**Issue by Philipose** [geoteo/dt-automated-config-audit#11]
Tenant V2 Changes matches the format of the V2 API but returns:

> AttributeError: 'NoneType' object has no attribute 'group'
plugin <RemotePluginEngine, meta_name:custom.remote.python.automated_configuration_audit id:0x21354182970> threw exception 'NoneType' object has no attribute 'group'
status changed for engine ('custom.remote.python.automated_configuration_audit', 123) PluginFullStatus(pluginName=custom.remote.python.automated_configuration_audit, pluginVersion=3.0.0, state=ERROR_UNKNOWN, description='NoneType' object has no attribute 'group', monitoredEntityId=0x7b, stacktrace=Traceback (most recent call last):   
  File "C:\Users\aaron.philipose\Gits\extension-automated-config\.venv\lib\site-packages\ruxit\plugin_state_machine.py", line 336, in _execute_next_task
    self._query_plugin()
  File "C:\Users\aaron.philipose\Gits\extension-automated-config\.venv\lib\site-packages\ruxit\plugin_state_machine.py", line 670, in _query_plugin
    self._plugin_run_data.plugin_instance._query_internal(**self._plugin_run_data.plugin_args)
  File "C:\Users\aaron.philipose\Gits\extension-automated-config\.venv\lib\site-packages\ruxit\api\base_plugin.py", line 452, in _query_internal
    return self.query(**kwargs)
  File "C:\Users\aaron.philipose\Gits\extension-automated-config\.\src\AuditActiveGatePlugin.py", line 195, in query
    self.process_audit_payload(audit_logs)
  File "C:\Users\aaron.philipose\Gits\extension-automated-config\.\src\AuditActiveGatePlugin.py", line 174, in process_audit_payload
    request_params=audit_v2_entry.extract_info(audit_log_entry, request_handler)
  File "C:\Users\aaron.philipose\Gits\extension-automated-config\.\src\AuditEntryV2Handler.py", line 42, in extract_info
    entity_id = entity_regex.group(2)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Philipose** [comment]
V2 Parser currently has a regex matcher to pull entites that match this format:

> builtin:alerting.connectivity-alerts (PROCESS_GROUP-EDF524FAA940FD7A): 25e635a0-96bb-3c0f-ba55-bf3fc40c10ea: \<no summary\>

tenant-wide changes look like this

> builtin:rum.user-experience-score (tenant): 3a4501ee-4b66-3682-b15d-9a6cb3963569: \<no summary\>

**Comment by Philipose** [comment]
V1 tenant detection example to check:

> APPLICATION_DETECTION_RULE: daab1579-ee84-48c5-9e3f-4caf12f58912
